version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=yourusername
      - DB_PASS=yourpassword
      - DB_NAME=yourdbname
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdbname
